language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: U6LWSbgw+/Qg/2qoTkYpneeChc/e0UBZPtejVkpWAElUvz29dbqm3E16IoBZu0Wm3u39x7HTOvcMQCQl14NQAPvusJHy5ggbX+guzCMcd796Zg483Tr9QA8BhAC7HvFZyYNnL7vhIH/DUF0SBvCMGBq/NSIPe64ftEiHie1A3omFQ/aTsODGBdIgUTCOPHDSZsQ6TR6SFaxIvhnA7tZUoos54XtRT+F7H9dHWBcSw151aOD2BIC7SdkTXZDQqdLyRWpqn60NvcRkUTpXZ1AR5lXMJ0tX5Lmg+Kik03hGfoQhejSJxVw8O85Crs5i1wm1a3rdNA9NZ8DavAHYXS0UEyp+SFxQVeBVaNhp/iKujenRH11yL4zIvh8S307H01xlXUCXs6Xhi3jDJQlYUQaw6LchXPQ0XHH9O8blKasfVQPxwXgh97fXUgrclDZB9dNQTNNedIWpEH4fWRn0yKHagxhNlfTNvHbyDx1YGCwJ2pLYQFx2vicQRBQ0sbuEeRBXPFXNr4Thf1Qh27PQxYSfH0m6QsrNuWFllepIB764FFPrkJ3QfXhOtehJkqGi8HUsHMM+T31XzDNdTTLDp1RukBD5w6qzIK36bdXGg/0v3tCq2/aWZOJVdG3NPsm42W5NUDQBdBFtlBS5jT93n/jse0tic+6QbAMuSlI8xBi6v10=
  app: agile-tor-49428
  on:
    repo: eako0508/theLittleThings-API
